### ISSUE TITLE
missing dependencies?

### ISSUE THREAD

**Issue by bvdberg** [panshak/arc#11]
When starting the server on Ubuntu 21.10 I get a missing dependency for Express.

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'express' imported from /home/user/arcinvoice/server/index.js

**Comment by Panshak** [comment]
Did you try to install express `npm install express` ?

**Comment by mayuri-dhote** [comment]
Hi @bvdberg and @Panshak,
I solved your issue for your missing dependency please use NPM INSTALL in both Client Application and Server Application.
It will resolve you problem

in Terminal run
> npm install      // install all required libs
![Screenshot (253)](https://user-images.githubusercontent.com/88150306/147062882-278f71d7-f60f-48f3-a917-0cf9d54258ee.png)

or 
> npm install express      // for install express lib Issue

I can able to see website and able to login

**Comment by panshak** [comment]
@mayuri-dhote Thank you.
