### ISSUE TITLE
Add way to include payment details

### ISSUE THREAD

**Issue by joekroese** [panshak/arc#15]
Love this software, thanks for releasing it!

On my invoices, I include my payment details so the client can pay me. I can't see a way to do that currently (but I could have missed it?). It would be great to have this feature.

**Comment by panshak** [comment]
@joekroese there is a section in the footer of the invoice where you can write your payment details and any other information. You'll see I named it as Notes/terms.

**Comment by joekroese** [comment]
I saw the Notes/terms section. The problem with using that for payment details is that I have to write my payment details there each time instead of them being copied over from previous data.

**Comment by panshak** [comment]
@joekroese okay, I get your point. I will include this in the next update.

**Comment by joekroese** [comment]
Amazing, thanks for your great work on this @panshak!

**Comment by panshak** [comment]
@joekroese, this feature has now been added. Go to profile settings, add your payment info and it'll appear across all new invoices.
